### ISSUE TITLE
Create examples of raw and annotated tabular data

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#10]
Have one or two realistic examples of raw (BIDS)

For age have an example:
- [x] with BIDS-conform age (float in years)
- [x] where age is not in years (but e.g. months)
- [x] of age as a range of values
- [ ] of age as a lower bound (with a `+`)
- [x] of age as a somewhat datetime string (ISO 8601)
- [x] of a column called age that clearly is mislabeled

For gender have an example
- [ ] for each BIDS conform version (e.g. f, F, female, FEMALE, Female)
- [ ] for BIDS conform sex but numerically mapped via data dictionary
- [x] for nonsensical gender (i.e. float, clearly mislabeled values)

**Comment by jarmoza** [comment]
Example participants tsv and json files for the categorization page can be placed in the assets folder for testing purposes
