### ISSUE TITLE
Understand how we can use Vuex for global state management

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#13]

**Comment by jarmoza** [comment]
Vuex's data store will be used as a means of storing data between the pages of the annotation tool – but *not* as a means of storing data between pages and their parent and child components as that somewhat breaks Vue's data model.

**Comment by surchs** [comment]
you are referring to this comment: https://stackoverflow.com/questions/57710800/when-should-i-use-vuex/63065612#63065612 ? OK, this makes some sense to me. I think we can go ahead and close this.

**Comment by jarmoza** [comment]
Yes, that's correct. Sounds good.
