### ISSUE TITLE
Store the classification of columns in the global store

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#18]
When a column is clicked on the categorization page and changes its color to reflect this (#3), then the column category should be stored in a global store that is accessible from all pages.

**Comment by surchs** [comment]
@jarmoza this still needs additional detail and an estimate.

**Comment by jarmoza** [comment]
Column painting color (and corresponding category - age, sex, subject_id, etc.) will be stored both at the page and store level. This is to ensure immediate access for the components during the current session, for the next steps (annotation and download), and for when sessions are interrupted and must be resumed. 

But an additional, interim storage place is likely necessary.

@surchs The notion of an interim session file should be discussed and implemented. I just created a new issue for this here: https://github.com/metaneuro/annotation_tool/issues/24

**Comment by jarmoza** [comment]
Closed by https://github.com/metaneuro/annotation_tool/pull/28
