### ISSUE TITLE
Review adding JS functions to vue page

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#20]
In order to add the functions in #16 and #17, I want to understand how to write and add JS functions in a vue page.

Some resources (any tips @jarmoza ?)
- vue mastery

Done would mean:
- [x] I have a clear sense of how to add functions to a Vue page
- [x] I have done this for the annotation page transformation for the age category (#16)

**Comment by jarmoza** [comment]
I learned via youtube tutorials. Though the person I was watching is still around, what I'm seeing is that NetNinja may be a good up to date resource on youtube.

That said, I think I'd stick with Vue mastery. They seem to have good tutorials and discussion on possible definitions for Vue javascript object (data, computed, mounted, props, watch, etc.)

**Comment by jarmoza** [comment]
Laracast Vue2 tutorial from 2017 is how I initially learned Vue: https://laracasts.com/series/learn-vue-2-step-by-step
