### ISSUE TITLE
Hook the transformation functions into the interface

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#21]
Given that we have transformation functions, raw data, and the necessary interface components to display all of this, we want to connect all of these components.

- [x] we decide what events should fire the transformation functions for age #16 and gender #17
- [x] connect the events that should fire the transformation 
- [x] decide where the raw and computed values should be stored (and loaded from for the purpose of showing them in the interface)
- [x] connect the raw value and computed values to the appropriate elements of the annotation interface (so that they get displayed)

**Comment by jarmoza** [comment]
@surchs Is this closable?

**Comment by surchs** [comment]
Indeed it is! Thanks for the nudge @jarmoza!
