### ISSUE TITLE
Create means of each page being capable of utilizing its own test data

### ISSUE THREAD

**Issue by jarmoza** [metaneuro/annotation_tool#25]
Each page should be able to be individually tested. The first step for that capability is to implement test data for each of the pages.

**Comment by surchs** [comment]
@jarmoza, do you have any thoughts on how to do that? It would be cool if I could use some testing data when I am working with the annotation page. Maybe we can agree on a simple format for the data coming out of the annotation step and implement that.

**Comment by surchs** [comment]
I think this has been solved now that the pages are connected and all access the store together.
