### ISSUE TITLE
Ensure that app state persists when moving between pages

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#30]
When I categorize columns on the categorization page (2), move to the annotation page (3) and then back to the categorization page (2), I should still see the same data as I had left it (i.e. columns of the loaded .tsv file are shown, color representations of their categorization are still there).

We should discuss what a valid way to move between pages should be 
- do we support the "back" button in the browser
- can people directly enter the route of a page and expect the data to still be there
- can I bookmark a page and expect data to still be there
- can I click on the navigation bar between pages without loosing data

**Comment by jarmoza** [comment]
This is mostly implemented (via #42) but some bugs remain (i.e. #50). When the latter is resolved, this can be closed out.

**Comment by jarmoza** [comment]
This issue/feature has long been resolved. Closing it.
