### ISSUE TITLE
Create component to show all columns mapped to a category for annotation page

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#57]
When I am on the annotation page and viewing e.g. the "Diagnosis" annotation view, I want to have a summary of all the columns that I had tagged to be "about" diagnosis in the categorization step, so that I can see if any of them don't make sense and go back to the categorization step to correct this.

**Input**:
- a pre-filtered list of all column names (and if available, their descriptions from the data dictionary) that have previously assigned to the current category

**Behaviour**:
- [ ] the component shows me a compact view of the columns I have assigned to the currently shown category
- [x] the component doesn't cover more than 1/3rd of vertical viewport space or else has the option to collapse
- [x] the component has some functionality to remove a column that was added in error. This could be either something that happens on the component and changes global annotation state. Or it could be a button that brings the user back to the categorization page

TODO
- [ ] document the format that the pre-filtered list of columns is supposed to be passed to the component
- [ ] document how the component retrieves or gets passed data from the (global) state on category tags and so on

**Comment by surchs** [comment]
At the moment I am just using the column name and the index to keep track of what columns were labeled for a given category. E.g.:

```javascript
columns_assigned_to_category: [
        { column_name: "Age", index: 1 },
        { column_name: "Time of acquisition", index: 4 },
      ]
```

**Comment by jarmoza** [comment]
@surchs And you're building this via `paintingData` in `$store.state.pageData.categorization`?

**Comment by surchs** [comment]
@jarmoza, I am just creating components for now, not hooking them up to any global state yet. I think that part we should discuss together and then decide how to do. So these components for now just have static internal data
