### ISSUE TITLE
Create component to validate numeric value mapping

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#59]
When a user annotates a category with continuous/numeric values like age, they need to be able to confirm that we are correctly transforming the raw values in columns they labeled as "about" age into our target format (e.g. years in float for age). There should also be a way for a user to tell us what the correct transformed value should be so we can take another attempt at getting the transformation right. 

**data in**:
- values from all columns labeled as about age (or another category we want represented numerically in the future)

**behaviour**:
- [x] I can see a selection of unique values (let's say no more than 5) in a table
- [ ] the table shows the unique, raw value as it appears in the participants.tsv table, and in a separate column our best guess for the transformed value
- [ ] As a user, if all the transformed values make sense, look good, then I can click a button below the table (e.g. "Confirm" or "Validate") to indicate that all is well in the world
- [ ] As a user, if one or several of the values are not transformed correctly, there is a textbox or other field where I can enter what the correct transformed value should be
- [ ] this textbox / field is either inside a third column in the table and on the same row as the incorrectly transformed value, or directly next to the table and locked (via layout) on the same height as the row of the incorrectly transformed value
- [ ] the textbox has some validation for numeric input (e.g. I should not be able to enter something that doesn't fit our target format)
- [ ] once I have entered anything valid in any textbox, the "validate" or "confirm" button below the table should become disabled
- [ ] there should be another button below the table that reads "re-transform" or something like that. 
- [ ] when I press the "re-transform" button, internally we should try to find a new transformation heuristic that satisfies the new information provided by the user. 
- [ ] once this new transformation is done, the user can validate the transformed values again
- [ ] if there is no heuristic that satisfies the values the user has entered, then we should show some type of error message and tell the user that we cannot find a way to transform the values into our target format. 

To be discussed
- we could provide the user with a single textfield to write a regex statement for us to transform the values with. this might help with hard cases.
-

**Comment by surchs** [comment]
In order to have control over the individual rows and still use bootstrap styling, I think we need to go with the ["simple table"](https://bootstrap-vue.org/docs/components/table#simple-tables) component from vue-bootstrap. 

So instead of: 

`<b-table striped hover :items="items"></b-table>`
styling everything, we will use  something like this:

```javascript
<b-table-simple hover>
    <b-thead>
      <b-tr>
        <b-th>Raw</b-th>
        <b-th>Column</b-th>
        <b-th>Value</b-th>
      </b-tr>
    </b-thead>
    <b-tbody>
      <b-tr v-for="row in unique_table_data">
        <b-td>{{ row.raw }}</b-td>
        <b-td>{{ row.column }}</b-td>
        <b-td><b-button variant="info" @click="handleButton(row.button)">correct</b-button></b-td>
      </b-tr>
    </b-tbody>
  </b-table-simple>
```
And then explicitly iterate over the rows. 
This gives us detailed control over each individual row, but we will probably have to hard-code the column names -- both of the table and of the data array we iterate over. I think this is a good tradeoff for now. We only need this kind of table for the age category for now. If we ever find out that this component is used in many other categories, we can think about doing the extra effort of making it more flexible.

**Comment by jarmoza** [comment]
I agree that it's easier to work with, though keep in mind that you do still have control over table properties. They're just accessed via keys in the entries in `items`. See https://bootstrap-vue.org/docs/components/table#field-definition-reference

Give the simple table a shot and see how it goes.

**Comment by surchs** [comment]
Aha, thanks @jarmoza, that is indeed an important point I had overlooked. Do you have an example of using `b-table` and inserting for example a button in the cells of one column like my above code snippet?

**Comment by surchs** [comment]
Just to be clear here: what gives me the ability to control rendering inside `b-table` is the combination of [scoped vue-slots](https://vuejs.org/guide/components/slots.html#scoped-slots) and the [vue-bootstrap syntax for scoped slots in the `b-table` template](https://bootstrap-vue.org/docs/components/table#scoped-field-slots), not the `fields` of the `b-table`. The `fields` definition you linked @jarmoza can be used to format the table, not individual rows. 

With scoped slots + `b-table` we save lines of code and have a cleaner component - but at the cost of a higher barrier of entry for contributors (need to understand vue scoped slots) and possibly also making it more difficult to change things. 

In the long run, this type of implementation might make it easier to adapt and re-use such a table component dynamically. But I do think that there is a real danger in trying to be "clever" and ending up with something incomprehensible. 

For now I'll implement with the `b-table` and then see what the end product looks like.

**Comment by jarmoza** [comment]
Take a look this @surchs, re: a button in a table: https://bootstrap-vue.org/docs/components/table#row-details-support

I agree. Frankly, the b-table with properties for dynamical style is a bit frustrating to me. So if you have a better way of doing it that's more intuitive - or mixes some dynamism in with it - I say go for it.

**Comment by surchs** [comment]
Yeah, thanks! The key element here are the vue scoped slots. They can even be [referred to dynamically](https://vuejs.org/guide/components/slots.html#dynamic-slot-names), which allows us to use plain JS to define their names. I think this will allow us to make the component reusable, but maybe at the expense of making things hard to understand. We'll need good docs focused at contributors!
