### ISSUE TITLE
How should we organize our components

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#60]
Since we are adding quite a number of components (e.g. #55, and there may be more in the future), I suggest that we organize components in subdirectories now. This is described in the [Nuxt docs](https://nuxtjs.org/docs/directory-structure/components/#nested-directories), but I [added a section to our wiki](https://github.com/metaneuro/annotation_tool/wiki/Nuxt-specific-information#nested-components-directories) just to be sure.

We should come up with a naming scheme for these directories.

_Originally posted by @surchs in https://github.com/metaneuro/annotation_tool/issues/55#issuecomment-1049066323_

**Comment by surchs** [comment]
Kind of evolved on my opinion on this in the meantime. Copying here since we discussed in https://github.com/metaneuro/annotation_tool/pull/77#issuecomment-1075355819

The reason I am back to preferring a flat list was that I read a [convincing piece on best practice](https://vueschool.io/articles/vuejs-tutorials/how-to-structure-a-large-scale-vue-js-application/) arguing against nested components. The bottom line was:

- flat dir gives you quick (visual and filter) access to components, no need to navigate dirs up and down
- what namespace control you get from nested dirs, you can also get from kebab-case naming the component itself. Vue treats both the same
- the components are (by default) alphabetically sorted, so stick together contextually

There are some other points in the piece. What convinced me most was that it gets pretty annoying to navigate all these sub-dirs (how deep should you go) and then you don't know where a new component should go. So I'd vote for keeping things flat until we find that this suggestion doesn't work for us.

Let me know what you think @jarmoza

**Comment by jarmoza** [comment]
@surchs After reading through, I agree and think we can close this issue.
