### ISSUE TITLE
Create a component to map raw values to vocabularies

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#63]
For our first iteration, we will only want to provide text fields to enter URIs from allowed vocabularies. But we can use the 
[`b-form-input` component](https://bootstrap-vue.org/docs/components/form-input), validate the input, and the visually display the outcome of the validation via [contextual states](https://bootstrap-vue.org/docs/components/form-input#contextual-states).

**Comment by jarmoza** [comment]
FYI: Bootstrap Vue docs have a hidden hash next to the subheadings that give you the anchor links for the subheading.

<img width="319" alt="Screen Shot 2022-02-25 at 3 46 45 PM" src="https://user-images.githubusercontent.com/4140162/155800636-e36fbff8-3883-44eb-aed4-d36227776e8f.png">

**Comment by surchs** [comment]
ah yes, thanks. I thought I had used that!
