### ISSUE TITLE
Variable category to color mapping by annotation 'flavor'

### ISSUE THREAD

**Issue by jarmoza** [metaneuro/annotation_tool#67]
In a previous discussion, @surchs and I discussed the possibility of having a more dynamic mapping between categories and colors.

Since the category list may differ depending on the kind of annotation the annotation tool user will engage in, it makes sense to add a dropdown for these flavors and corresponding code to make that mapping a computed property (on the page the dropdown sits, but saved in the store).

The current solution is in the upcoming PR (https://github.com/metaneuro/annotation_tool/pull/66) where a `categoryToColorMap` sits in the store.

**Comment by jarmoza** [comment]
Possibly linked to https://github.com/metaneuro/annotation_tool/issues/12

**Comment by surchs** [comment]
I think this is addressed with #66
