### ISSUE TITLE
Suggested commits for state and column to category map setup

### ISSUE THREAD

**Issue by jarmoza** [metaneuro/annotation_tool#73]
Seb suggested two changes to PR #66 that were not added with its merge with the main branch.

This issue is here for notes and discussion on those.

The first is a suggestion on making the column to category map setup function more compact: https://github.com/metaneuro/annotation_tool/pull/66/commits/cf94902944319e8a1348890d1b4414603e0423a7

The second - which is a larger discussion - is the moving of state knowledge to the global store. This will require more changes than are in this commit. Namely, changes to the store script.
https://github.com/metaneuro/annotation_tool/pull/66/commits/a0e79d4fb4bd81448fa20f8bb14fc60ae0778e8c

**Comment by surchs** [comment]
Both are now addressed in #108
