### ISSUE TITLE
Decide on minimal code style

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#74]
Now that we're working on overlapping pieces of code, we need to adapt a minimal code style so our commits don't become spammed by fluffy formatting diffs. 

I suggest we agree on 
- 4 space indentation (not tab)
- emtpy newline at the end of the file

anything else? Mostly focused on avoiding useless diffs for now.

**Comment by jarmoza** [comment]
One thing that could fall into this category. We should have semicolons at the end of every JS statement and not rely on automatic semicolon insertion.

**Comment by surchs** [comment]
OK, thanks for pointing this out! I think we should just get this over with while we're add it and just adapt an actual (existing) code style and set up a linter and formatter for it.
