### ISSUE TITLE
Improve legibility of computed props in the annotation pages

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#82]
This is an issue from the PR that we decided to address later because of the upcoming demo and to proceed with the core functionality of the PR faster. Here are the comments @jarmoza made in the PR:

> Complex return values (see examples `filteredTable`, `uniqueValues`, `unique_table_data`, `applyTransform` in `annot-age-values.vue` and `filteredColumns` in `annot-columns.vue`):

- Though it's tempting to use this kind of syntax to produce a return value in one line, code like this becomes confusing for people who are approaching it. I would recommend breaking down this return value creation process into several lines before the final value is returned.

- As I mention in one comment in `annot-columns.vue`, maybe we should institute some rule for the number of levels deep a (return) statement can be before it should be broken up into several distinct steps in our code.

_Originally posted by @jarmoza in https://github.com/metaneuro/annotation_tool/pull/77#pullrequestreview-916367338_

**Comment by surchs** [comment]
@jarmoza take a look and let me know if we should close this

**Comment by jarmoza** [comment]
It's good to close. This was handled in PR #108
