### ISSUE TITLE
dataTable.annotated should initialize as a copy of dataTable.original

### ISSUE THREAD

**Issue by surchs** [metaneuro/annotation_tool#96]
Because of #94 we need to make sure that dataTable.annotated is not null when we first load the annotation page so we can pass it down as a prop to our annotation components.

This also affects the current pageAccess state for the download page so we will have to find an alternative solution to detect when the download page should become accessible.

**Comment by jarmoza** [comment]
Fixed as of #97 . Closing this issue.
